### ISSUE TITLE
`--packages` should be used over `-ppackages`

### ISSUE THREAD

**Issue by daniel-v** [pulyaevskiy/node-interop#13]
As per: dart-lang/build#1171

**Comment by Cretezy** [comment]
#8

**Comment by Cretezy** [comment]
https://github.com/Cretezy/node-interop/tree/new-frontend for future fix when scratch_space publishes 0.2.0.

**Comment by Cretezy** [comment]
https://github.com/pulyaevskiy/node-interop/pull/14

Done!

**Comment by pulyaevskiy** [comment]
Waiting for tests to pass and will publish 0.1.1 right after

**Comment by pulyaevskiy** [comment]
https://pub.dartlang.org/packages/build_node_compilers

Thanks again @Cretezy !
