### ISSUE TITLE
NodeClient fails to parse headers on response if a JSArray is included

### ISSUE THREAD

**Issue by TonyDowney** [pulyaevskiy/node-interop#18]
`final headers = new Map<String, String>.from(dartify(response.headers));`

This line in node_http.dart throws a TypeError if the headers include a JSArray. The `.from()` call can't turn the JSArray into a basic type, so it complains that it can't turn it into a String:

> TypeError: Instance of 'JSArray': type 'JSArray' is not a subtype of type 'String'
>     at wrapException (/user_code/build/node/index.dart.js:4440:17)
>     at assertSubtypeOfRuntimeType (/user_code/build/node/index.dart.js:5315:17)
>     at JsLinkedHashMap.$indexSet (/user_code/build/node/index.dart.js:6288:11)
>     at LinkedHashMap_LinkedHashMap$from_closure.call$2 (/user_code/build/node/index.dart.js:10190:21)
>     at JsLinkedHashMap.forEach$1 (/user_code/build/node/index.dart.js:6370:18)
>     at J.forEach$1$ax (/user_code/build/node/index.dart.js:43865:42)
>     at LinkedHashMap_LinkedHashMap$from (/user_code/build/node/index.dart.js:9571:9)
>     at NodeClientHeadersFix_send_handleResponse.dart.NodeClientHeadersFix_send_handleResponse.call$1 (/user_code/build/node/index.dart.js:43042:21)
>     at Primitives_applyFunctionWithPositionalArguments (/user_code/build/node/index.dart.js:4367:28)
>     at Function_apply (/user_code/build/node/index.dart.js:12105:14)

Not sure if this is a fault in javascript parsing the headers, `dartify()` not running recursively, or just an unconsidered use case.

My solution, which eliminates the `.from()` call (but likely introduces new problems):
```
Map headersTemp = dartify(response.headers);
Map headers = new Map<String, String>();
for (var key in headersTemp.keys){
  headers[key.toString()] = headersTemp[key].toString();
}
```

**Comment by pulyaevskiy** [comment]
Thanks for reporting! This looks like a bug on node_http side, but I just tried to reproduce this error in a test case and had no luck so far.

Could you provide version of Dart SDK you used to compile your code? 
Also wondering which header specifically contains `JSArray` if you have this information?

**Comment by TonyDowney** [comment]
dart/2.0.0-dev.48.0

I'll send you a private message with a URL for testing. I believe it's having an access-control-allow-headers header with a huge list of values that's problematic.

**Comment by pulyaevskiy** [comment]
Thanks for the info.

Looks like the issue is with `set-cookie` headers, which is treated as an array by Node.

I think I'm going to implement logic similar to that of IO client:

```dart
      var headers = <String, String>{};
      response.headers.forEach((key, values) {
        headers[key] = values.join(',');
      });
```

From here: https://github.com/dart-lang/http/blob/0fc840ff18ce96188f361b3649bb99f4814be4ba/lib/src/io_client.dart#L60-L63

I better way would be for BaseResponse to expose `HttpHeaders` instead of a `Map`, but this needs to be changed in the `http` package itself.

**Comment by pulyaevskiy** [comment]
Just published https://pub.dartlang.org/packages/node_http/versions/1.0.0-dev.3.0 which should fix this for you.

Thanks again for taking time to report this issue!
