### ISSUE TITLE
InternetAddress implementation

### ISSUE THREAD

**Issue by pulyaevskiy** [pulyaevskiy/node-interop#3]
Work has started here:

- https://github.com/pulyaevskiy/node-interop/blob/master/lib/src/internet_address.dart

Need to finalize, but there looks like no support for parsing IPs in to their `in_addr` format in Node. Might just throw `UnsupportedError` to start with.

**Comment by CedX** [comment]
For my part, I ended up using the [`ipaddr.js`](https://www.npmjs.com/package/ipaddr.js) package.
See: https://github.com/cedx/nodejs-interop.dart/blob/master/lib/src/io/socket/internet_address.dart

That's what a Node.js developer would have done (i.e. use a dedicated npm module). I did not have the courage to translate the JS code of the `ipaddr.js` package to Dart code...

Clearly not a satisfying solution but it works.

**Comment by pulyaevskiy** [comment]
Thanks for the feedback!

Looking now at my original comment I'm not sure why I needed `in_addr` actually. Just looked at the interface again and feel like there is no real blockers, but as you said just need to either port some logic from that npm package, or I also thought it would be worth looking in the Dart VM source code to make sure behavior is identical.

**Comment by pulyaevskiy** [comment]
Oh, I think I was looking for `in_addr` because native implementation uses `inet_pton` C function which is platform-dependent.

**Comment by pulyaevskiy** [comment]
FYI: I ended up implementing what `inet_pton` is doing, published as `1.0.0-dev.2.0`.

**Comment by CedX** [comment]
Wise decision to use a v1.0-dev tag because v0.1 tag did not give justice to your library that I find more advanced than mine :) great work !
