### ISSUE TITLE
Consider exposing __filename

### ISSUE THREAD

**Issue by alextekartik** [pulyaevskiy/node-interop#32]
When using firebase cloud functions, the only way (I am aware of according to https://cloud.google.com/functions/docs/concepts/exec#file_system) to get the functions directory (when deployed) is to use `__dirname` or `__filename` (assuming the js file is at the root of this directory)

This is needed if you want to read a deployed filed in the functions directory.
So far looking at your bootstrap code, I was able to use:
```dart
@JS("self.location.href")
external String get filename;
```

Maybe there should be a more official/reliable way. Thanks!

**Comment by pulyaevskiy** [comment]
You also have a couple other options available.

### Use ‘node_io’ package

This is my preferred way:


```dart
import ‘package:node_io/node_io.dart’;

void main() {
  // You can get current directory with:
  Directory dir = Directory.current;
  // Or you can get path of the script being executed:
  Uri script = Platform.script;
}
```
Not sure which one would work better for you, you probably need to experiment with these.
### Use ‘node_interop’ directly

```dart
import ‘package:node_interop/node.dart’;

void main() {
  // Get current directory:
  String dir = process.cwd();
  // Get main module’s filename:
  String file = module.filename;
}
```

**Comment by pulyaevskiy** [comment]
I should mention though that FS module in node_io is half implemented :-) some methods on File and Directory would through Unimplemented error. Didn’t get around to finish this yet.

**Comment by alextekartik** [comment]
Ok thanks, sorry I missed these alternatives (Directory.current definitely not the one I need - as the firebase doc said the current directory might not be the functions dir - so will try the others)

**Comment by pulyaevskiy** [comment]
No worries. I’m curious which will work for you in the end, please let me know how it goes! And feel free to re-open if it doesn’t work.
