### ISSUE TITLE
Feature Request (or, How-to?): followRedirect HTTP 3xx Behaviour

### ISSUE THREAD

**Issue by paulreimer** [pulyaevskiy/node-interop#39]
Not sure how/where to enable this for `node_http` requests, but I would like to recursively follow HTTP responses with response code 3xx. In the node `request` module it is called "followRedirect" and/or "followAllRedirects". Hopefully it is already possible and just harder to find the config options (but I am also curious where to look to find out whether features like this are already supported)

**Comment by pulyaevskiy** [comment]
Thanks for taking time to submit this issue.

You are right, this feature is not implemented yet. Shouldn't be too hard to add it though, I'll try to have an update by the end of this week.

**Comment by pulyaevskiy** [comment]
@paulreimer I just published an update to node_http which includes basic support for `followRedirects`. Details are in #40.

Let me know how it works for you.

**Comment by paulreimer** [comment]
Awesome! Works great.

Nice work on some loop detection also. I guess `maxRedirects` is coming from the interop, and the default value is 10. But it is working as expected for me!

**Comment by pulyaevskiy** [comment]
`maxRedirects` actually comes from `dart:io`  and current implementation is heavily inspired by `dart:io` code. I think defaults are also coming from either `http` package or `dart:io`.

Thanks for confirming! I'm closing this issue, but feel free to file new ones if you find a bug or have other suggestions.
