### ISSUE TITLE
HTTP POST request returns 411 status code

### ISSUE THREAD

**Issue by kostaa** [pulyaevskiy/node-interop#48]
I am getting 411 status code reply from a http post request that is running inside a cloud function.  Do I need to set `Content-Length` property or is this handled further down the stack? I have also tried setting `transfer-encoding:chunked` but that did not make any difference.

```dart
import 'package:node_http/node_http.dart' as http;
     // ....

     Map<String, String> headers = {
      'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8',
    };

    Map<String, String> body = {
      'redirect_uri': apiDesc.redirectEndpoint,
      'grant_type': 'authorization_code',
      'code': code
    };

    if (basicAuth && isNotNull(apiDesc.clientSecret)) {
      headers["Authorization"] = 'Basic ' +
          base64Encode(ascii.encode(Uri.encodeFull(apiDesc.clientId)
              + ':' + Uri.encodeFull(apiDesc.clientSecret)));
    } else {
      body["client_id"] = apiDesc.clientId;
      if (isNotNull(apiDesc.clientSecret))
        body["client_secret"] = apiDesc.clientSecret;
    }

    http.Response resp = await http.post(
        apiDesc.tokenEndpoint,
        headers: headers,
        body: body);
```

**Comment by pulyaevskiy** [comment]
Interesting. I just implemented `authorization_code` grant for Google APIs yesterday and it worked for me. They use json though.

Is it a public OAuth server you're trying to hit or your own?

I'd like to find a way to reproduce this error reliably before attempting to fix it.
It does look like `content-length` is missing...

**Comment by pulyaevskiy** [comment]
FYI: I moved this issue to node_interop as it's not related to Firebase Functions.

In short, after looking at existing implementations in `dart:io` and `package:http` they are not handling `Content-Length` themselves. I suspect this is because it can be limiting and prevent some use cases.

So, I'm a bit hesitant to add this functionality to the NodeClient, I'd like it to follow semantics of existing implementations when possible.

This means you'd need to set `content-length` header yourself.

**Comment by kostaa** [comment]
Fair enough thanks for looking into it.

**Comment by kostaa** [comment]
Just a thought - maybe you could add another named parameter say `setContentLength` that would default to `false` and follow the existing semantics.  By setting it explicitly to `true` the `Content-Length` header would be added. 

`void post(url,{Map<String, String> headers, body, Encoding encoding, bool setContentLength = false})`

**Comment by pulyaevskiy** [comment]
Thanks, I'll think about it. It might break contract of `Client` interface provided by `http` package, but I'm not sure.

**Comment by kostaa** [comment]
You are right this not the best suggestion :)
