### ISSUE TITLE
HttpResponse.redirect() throws an exception

### ISSUE THREAD

**Issue by kostaa** [pulyaevskiy/node-interop#49]
I am getting an exception when calling a redirect from a cloud function.

`Invalid argument(s): object must be a Map or Iterable at Object.b (/srv/build/node/index.dart.js:1409:3) 
...
`

Not sure if I am missing anything here. This is a short test version:

` functions['redirectTest'] = FirebaseFunctions.https.onRequest(
    (ExpressHttpRequest rq) => rq.response.redirect(Uri.parse('https://www.bbc.co.uk')));
`

**Comment by pulyaevskiy** [comment]
Yes, that's a bug. Thanks for submitting!

I just published `node_io 1.0.0-dev.10.0` which should fix this issue for you. Make sure to run `pub upgrade` to get latest version.

Closing this as resolved but feel free to re-open if the issue persists.

**Comment by kostaa** [comment]
Great thanks.
