### ISSUE TITLE
Bump http to 0.12

### ISSUE THREAD

**Issue by timtraversy** [pulyaevskiy/node-interop#53]
Hello! Thanks for all the excellent work on node and firebase interop for Dart, it's a lifesaver! Can the http dep in `node_http` be bumped from `0.11.3` to a more modern version (currently `http 0.12.0+1`)? `0.11.3` is from 2015 and clashes with newer libraries. Thanks!

**Comment by timtraversy** [comment]
Not sure if submitting a PR would trigger tests or if you have to run them locally.

**Comment by pulyaevskiy** [comment]
Thanks for reporting! Fix is on the way (assuming this is for `node_http` package), will have a new release later today.

**Comment by timtraversy** [comment]
Great, thanks!

**Comment by pulyaevskiy** [comment]
Sorry for the delay. I just published `1.0.0` (decided to bump to stable as the lib has been working without any issues or bug reports for a while).

https://pub.dartlang.org/packages/node_http

Thanks again for taking time to report this!
