### ISSUE TITLE
Process.argv doesn't have a reified type

### ISSUE THREAD

**Issue by nex3** [pulyaevskiy/node-interop#56]
The `Process.argv` getter declares a reified type of `List<String>`, but because the array in question comes from JS, it doesn't have a reified `String` type argument. This causes it to throw an error at runtime when passed to pure Dart code that expects a `List<String>`.

Once https://github.com/dart-lang/sdk/issues/30554 is fixed, it will be possible to modify the `argv` getter so that it casts the array when accessed from Dart. Until then, it's probably best to make the static type just `List` so that we get appropriate static errors.

**Comment by pulyaevskiy** [comment]
I just wrote following test which worked for some reason:

```dart
@TestOn('node')
import 'package:node_interop/node_interop.dart';
import 'package:test/test.dart';

void main() {
  group('process', () {
    test('argv', () {
      foo(process.argv);
    });
  });
}

void foo(List<String> args) {
  print(args);
}
```

Tested on Dart SDK 2.3.0. Am I missing something here?

**Comment by nex3** [comment]
It looks like dart2js is inlining the call to `foo()`, which gets rid of the runtime type check. You can tell it not to do that using [`@noInline`](https://pub.dev/documentation/meta/latest/meta_dart2js/noInline-constant.html):

```dart
import 'package:meta/dart2js.dart';
import 'package:node_interop/node_interop.dart';
import 'package:test/test.dart';

void main() {
  group('process', () {
    test('argv', () {
      foo(process.argv);
    });
  });
}

@noInline
void foo(List<String> args) {
  print(args);
}
```

**Comment by pulyaevskiy** [comment]
Thanks, good to know! Will give it another round over the weekend.

**Comment by alextekartik** [comment]
I remember having a similar issue sometime ago on this where I add to reimplement `process.argv`.  Other simple test that shows the issue (without the noInline trick)

```dart
test('argv', () {
  expect(process.argv, const TypeMatcher<List<dynamic>>()); // success
  expect(process.argv, const TypeMatcher<List<String>>()); // failure
});
```

**Comment by pulyaevskiy** [comment]
I just pushed `1.0.3` with no generic type arguments for Process methods.

There is likely more similar cases in other places, which I'll tackle separately.

Thanks for your help!
