### ISSUE TITLE
node_io (http and file) not compatible with SDK 2.5

### ISSUE THREAD

**Issue by alextekartik** [pulyaevskiy/node-interop#62]
2.5 has landed on dart dev and some changes (List<int> to Uint8List) breaks the node_io package for openRead, readAsBytes and Http response.

(Ok I just noticed the PR here: https://github.com/pulyaevskiy/node-interop/pull/61)

**Comment by pulyaevskiy** [comment]
I merged #61 but there are still issues with `File` methods. 

@tvolkert are we supposed to update `openRead` and others to `UInt8List` as well? I read through https://github.com/dart-lang/sdk/issues/36900 but I'm still not sure what's the recommended strategy here.

**Comment by pulyaevskiy** [comment]
I submitted #63 with `openRead` fix.

**Comment by pulyaevskiy** [comment]
Sorry forgot to update here: this should be fixed in latest release. Closing but feel free to re-open if something is not addressed still.
