### ISSUE TITLE
Add pedantic rules in analysis_options.yaml

### ISSUE THREAD

**Issue by alextekartik** [pulyaevskiy/node-interop#65]
May I suggest adding

```
include: package:pedantic/analysis_options.yaml
```

in all your analysis_options.yaml (https://dart.dev/guides/language/analysis-options#default-google-rules-pedantic). It will likely raise lots of warning but could help pinpoint some issues. Thanks!

**Comment by pulyaevskiy** [comment]
I just pushed this change to all packages as well as fixed all the warnings.

Thanks for suggestion!
